package br.pro.luciene.exemplomvc.view;

import br.pro.luciene.exemplomvc.control.UsuarioController;
import br.pro.luciene.exemplomvc.model.Usuario;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class JfCadastroPessoa extends javax.swing.JDialog {

    private Usuario usuario;
    private UsuarioController usuarioCtrl;
    private DefaultTableModel modelo;
    private ArrayList<Usuario> listaUsuarios;
    
    /**
     * Creates new form JfCadastroPessoa
     * @param parent
     * @param modal
     */
    public JfCadastroPessoa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
            initComponents();
            
        try {            
            usuarioCtrl = new UsuarioController();
            modelo = (DefaultTableModel) jTableLogin.getModel();
            listaUsuarios = new ArrayList<>();
        } catch (Exception ex) {
            Logger.getLogger(JfCadastroPessoa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlblID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtSenha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLogin = new javax.swing.JTable();
        jcbCampo = new javax.swing.JComboBox();
        jtPesquisa = new javax.swing.JTextField();
        jBtnExcluir = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jTxtLogin = new javax.swing.JTextField();
        jBtnVerTodos = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 70, 14);

        jlblID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblID.setText("0");
        getContentPane().add(jlblID);
        jlblID.setBounds(86, 50, 40, 14);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Login:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 84, 70, 14);

        jTxtSenha.setEnabled(false);
        getContentPane().add(jTxtSenha);
        jTxtSenha.setBounds(90, 110, 290, 20);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 120, 70, 14);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuários"));
        jPanel1.setLayout(null);

        jLabel6.setText("Selecione o campo de pesquisa e digite o argumento:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 50, 390, 14);

        jTableLogin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Login", "Senha"
            }
        ));
        jScrollPane1.setViewportView(jTableLogin);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 530, 190);

        jcbCampo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Id", "Login", "Senha" }));
        jPanel1.add(jcbCampo);
        jcbCampo.setBounds(26, 80, 160, 26);

        jtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisaKeyReleased(evt);
            }
        });
        jPanel1.add(jtPesquisa);
        jtPesquisa.setBounds(200, 80, 350, 24);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 200, 560, 310);

        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setEnabled(false);
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExcluir);
        jBtnExcluir.setBounds(240, 170, 90, 23);

        jBtnSalvar.setText("Salvar");
        jBtnSalvar.setEnabled(false);
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalvar);
        jBtnSalvar.setBounds(180, 140, 80, 23);

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.setEnabled(false);
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancelar);
        jBtnCancelar.setBounds(270, 140, 100, 23);

        jTxtLogin.setEnabled(false);
        getContentPane().add(jTxtLogin);
        jTxtLogin.setBounds(90, 80, 290, 20);

        jBtnVerTodos.setText("Ver Todos");
        jBtnVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerTodosActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnVerTodos);
        jBtnVerTodos.setBounds(480, 520, 90, 23);

        jBtnEditar.setText("Editar");
        jBtnEditar.setEnabled(false);
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEditar);
        jBtnEditar.setBounds(140, 170, 90, 23);

        jBtnNovo.setText("Novo");
        jBtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnNovo);
        jBtnNovo.setBounds(80, 140, 90, 23);

        setSize(new java.awt.Dimension(631, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        limparCampos();
        tratarCampos(true); //habilitar os campos
        jBtnSalvar.setEnabled(true);
        jBtnCancelar.setEnabled(true);
        jBtnExcluir.setEnabled(false);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        limparCampos();
        tratarCampos(false); //habilitar os campos
        jBtnSalvar.setEnabled(false);
        jBtnCancelar.setEnabled(false);
        jBtnExcluir.setEnabled(true);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        limparCampos();
        tratarCampos(false); //habilitar os campos
        jBtnSalvar.setEnabled(false);
        jBtnCancelar.setEnabled(false);
        jBtnExcluir.setEnabled(true);
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jBtnVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnVerTodosActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnNovoActionPerformed

    private void jtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisaKeyReleased
        try {
           
            if (jtPesquisa.getText().length() >= 1) {
                String campo = jcbCampo.getSelectedItem().toString();
                String textoPesquisa = jtPesquisa.getText();
                
                listaUsuarios = usuarioCtrl.pesquisar(campo, textoPesquisa);
                modelo.setNumRows(0);
                
/*                
                //uma forma de fazer
                
                //listaUsuarios.stream().forEach((usuario) -> {
                for (Usuario usuario : listaUsuarios) {
                  modelo.addRow(new Object[] {
                      usuario.getId(),
                      usuario.getLogin(),
                      usuario.getSenha()
                  });    
                }
*/
                
                for (int i=0; i < listaUsuarios.size(); i++) {
                    modelo.addRow(new String[] {
                      String.valueOf(listaUsuarios.get(i).getId()),
                      listaUsuarios.get(i).getLogin(),
                      listaUsuarios.get(i).getSenha()
                  });    
                }
                    
                
                
            } else {
                //limpa a tabela
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro: "+
                    erro.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }        
        
        
        
    }//GEN-LAST:event_jtPesquisaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JfCadastroPessoa dialog = new JfCadastroPessoa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JButton jBtnVerTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLogin;
    private javax.swing.JTextField jTxtLogin;
    private javax.swing.JTextField jTxtSenha;
    private javax.swing.JComboBox jcbCampo;
    private javax.swing.JLabel jlblID;
    private javax.swing.JTextField jtPesquisa;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        jTxtSenha.setText(null);

        //limpar a tabela
        /*
        jTableContato.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nome", "DDD", "Telefone", "Operadora"
                }
        ));
        */
        
        modelo.setNumRows(0);
    }

    private boolean preencherObjeto() throws Exception {

        return true;
    }

    private boolean validarCampos() throws Exception {
        String msg = "";
        
        if (jTxtSenha.getText().equals("")) {
            msg+="\nO campo nome não pode ser vazio";
            jTxtSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        } else if (jTxtSenha.getText().length() > 50) {
            msg+="\nO nome não pode ter mais de 50 caracteres";
        }
        

        //colocar os demais campos
        
        if (msg.length() == 0)
            return true;
        else {
            JOptionPane.showMessageDialog(null, msg);
            return false;
        }
    }

    private void tratarCampos(boolean f) {
        jTxtSenha.setEnabled(f);
        jBtnExcluir.setEnabled(f);
        jBtnSalvar.setEnabled(f);
        jBtnCancelar.setEnabled(f);
    }

}
