/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.pro.luciene.exemplomvc.view;

import br.pro.luciene.exemplomvc.control.UsuarioController;
import br.pro.luciene.exemplomvc.model.Usuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Basseti
 */
public class JFCadUsuario extends javax.swing.JDialog {

    private Usuario usuario;
    private UsuarioController usuarioController;

    /**
     * Creates new form JFCadUsuario
     *
     * @param parent
     */
    public JFCadUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        usuario = new Usuario();
        
        
        try {
            usuarioController = new UsuarioController();
        } catch (Exception ex) {
            Logger.getLogger(JFCadUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtLogin = new javax.swing.JTextField();
        jBtnNovo = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jTxtSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Login:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(69, 112, 50, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(64, 154, 60, 17);
        getContentPane().add(jTxtLogin);
        jTxtLogin.setBounds(130, 110, 160, 30);

        jBtnNovo.setText("Novo");
        jBtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnNovo);
        jBtnNovo.setBounds(70, 230, 90, 30);

        jBtnSalvar.setText("Salvar");
        jBtnSalvar.setEnabled(false);
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalvar);
        jBtnSalvar.setBounds(170, 230, 100, 30);

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.setEnabled(false);
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancelar);
        jBtnCancelar.setBounds(280, 230, 100, 30);
        getContentPane().add(jTxtSenha);
        jTxtSenha.setBounds(130, 150, 160, 30);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 120, 73, 23);

        setSize(new java.awt.Dimension(451, 351));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoActionPerformed
        limparCampos();
        tratarCampos(true);
        jBtnNovo.setEnabled(false);
        jBtnSalvar.setEnabled(true);
        jBtnCancelar.setEnabled(true);
    }//GEN-LAST:event_jBtnNovoActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        limparCampos();
        tratarCampos(false);
        jBtnNovo.setEnabled(true);
        jBtnSalvar.setEnabled(false);
        jBtnCancelar.setEnabled(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String passString = new String(jTxtSenha.getPassword());
        System.out.print(passString);
        System.out.print(String.copyValueOf(jTxtSenha.getPassword()));

        try {
            this.validarCampos();
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    //incluir no banco
                    if (usuarioController.incluir(usuario)) {
                        JOptionPane.showMessageDialog(null, "Salvo", "Informação", JOptionPane.INFORMATION_MESSAGE);
                    }
                    jBtnCancelarActionPerformed(evt);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(JFCadUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JFCadUsuario dialog = new JFCadUsuario(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTxtLogin;
    private javax.swing.JPasswordField jTxtSenha;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        jTxtLogin.setText(null);
        jTxtSenha.setText(null);
    }

    private boolean validarCampos() throws Exception {
        String msg = "";

        if (jTxtLogin.getText().trim().length() < 3 || jTxtLogin.getText().trim().length() > 15) {
            msg += "\nO Login deve ter no mínimo 3 e no máximo 15 caracteres!";
        }

        if (String.copyValueOf(jTxtSenha.getPassword()).trim().length() < 3
                || String.copyValueOf(jTxtSenha.getPassword()).trim().length() > 15) {
            msg += "\nA Senha deve ter no mínimo 3 e no máximo 15 caracteres!";
        }

        if (msg.equals("")) {
            return true;
        } else {
            throw new Exception(msg);
        }
    }

    private boolean preencherObjeto() throws Exception {
        usuario.setLogin(jTxtLogin.getText());
        usuario.setSenha(String.copyValueOf(jTxtSenha.getPassword()));

        return true;
    }

    private void tratarCampos(boolean f) {
        jTxtLogin.setEnabled(f);
        jTxtSenha.setEnabled(f);
    }

}
